[book]
authors = ["Ankitects Pty Ltd and contributors"]
description = "Frequently asked questions about Anki. Anki is a program that makes learning easier."
language = "en"
multilingual = false
src = "src"
title = "Anki FAQs"

[build]
create-missing = true

[output.html]
no-section-label = true
git-repository-url = "https://github.com/ankitects/faqs/"
additional-css = ["css/misc.css"]

[output.linkcheck]
optional = true
warning-policy = "warn"
follow-web-links = true
# sites that block programmatic access
exclude = [ 'quora\.com', 'reddit.com', 'superuser.com', 'github.com/open-spaced-repetition' ]

[output.html.redirect]
# redirect deleted pages to new pages to preserve legacy links
"note-types-with-strange-names.html" = "https://docs.ankiweb.net/faqs/removing-duplicate-note-types"

"/index.html" = "https://docs.ankiweb.net/faqs/intro"
"/can-i-reveal-parts-of-a-card-one-at-a-time.html" = "https://docs.ankiweb.net/faqs/can-i-reveal-parts-of-a-card-one-at-a-time" 
"/outlook-silently-discards-email.html" = "https://docs.ankiweb.net/faqs/outlook-silently-discards-email" 
"/when-problems-occur.html" = "https://docs.ankiweb.net/faqs/when-problems-occur" 
"/due-times-after-a-break.html" = "https://docs.ankiweb.net/faqs/due-times-after-a-break" 
"/anki-knockoffs.html" = "https://docs.ankiweb.net/faqs/anki-knockoffs" 
"/getting-help.html" = "https://docs.ankiweb.net/manual/getting-help"
"/resetting-progress-in-a-deck.html" = "https://docs.ankiweb.net/faqs/resetting-progress-in-a-deck" 
"/emails-not-being-received.html" = "https://docs.ankiweb.net/faqs/emails-not-being-received" 
"/changing-the-font.html" = "https://docs.ankiweb.net/faqs/changing-the-font" 
"/ankidroid-has-a-separate-support-site.html" = "https://docs.ankiweb.net/faqs/ankidroid-has-a-separate-support-site" 
"/study-in-a-particular-order.html" = "https://docs.ankiweb.net/faqs/study-in-a-particular-order" 
"/restoring-an-automatic-backup-recovering-from-data-loss.html" = "https://docs.ankiweb.net/faqs/restoring-an-automatic-backup-recovering-from-data-loss" 
"/anki-is-not-showing-me-all-my-cards.html" = "https://docs.ankiweb.net/faqs/anki-is-not-showing-me-all-my-cards" 
"/media-files-may-take-time-to-sync.html" = "https://docs.ankiweb.net/faqs/media-files-may-take-time-to-sync" 
"/text-to-speech-support.html" = "https://docs.ankiweb.net/faqs/text-to-speech-support" 
"/splitting-a-field-into-multiple-fields.html" = "https://docs.ankiweb.net/faqs/splitting-a-field-into-multiple-fields" 
"/are-there-limits-on-file-sizes-on-ankiweb.html" = "https://docs.ankiweb.net/faqs/are-there-limits-on-file-sizes-on-ankiweb" 
"/shortcut-not-working.html" = "https://docs.ankiweb.net/faqs/shortcut-not-working" 
"/learning-steps-skipped-or-repeated.html" = "https://docs.ankiweb.net/faqs/learning-steps-skipped-or-repeated" 
"/how-can-i-work-with-someone-else-to-create-a-deck.html" = "https://docs.ankiweb.net/faqs/how-can-i-work-with-someone-else-to-create-a-deck" 
"/can-i-sync-only-some-of-my-decks.html" = "https://docs.ankiweb.net/faqs/can-i-sync-only-some-of-my-decks" 
"/removing-duplicate-note-types.html" = "https://docs.ankiweb.net/faqs/removing-duplicate-note-types" 
"/linking-cards-together.html" = "https://docs.ankiweb.net/faqs/linking-cards-together" 
"/timestamps-in-the-future.html" = "https://docs.ankiweb.net/faqs/timestamps-in-the-future" 
"/error-establishing-a-secure-connection-when-syncing.html" = "https://docs.ankiweb.net/faqs/error-establishing-a-secure-connection-when-syncing" 
"/sounds-or-images-are-not-appearing-on-ankiweb-or-the-mobile-clients.html" = "https://docs.ankiweb.net/faqs/sounds-or-images-are-not-appearing-on-ankiweb-or-the-mobile-clients" 
"/shared-decks-with-broken-javascript.html" = "https://docs.ankiweb.net/faqs/shared-decks-with-broken-javascript" 
"/requesting-a-refund-for-ankimobile.html" = "https://docs.ankiweb.net/faqs/requesting-a-refund-for-ankimobile" 
"/extra-copies-of-a-card-are-coming-up.html" = "https://docs.ankiweb.net/faqs/extra-copies-of-a-card-are-coming-up" 
"/ankiweb-account-removal.html" = "https://docs.ankiweb.net/faqs/ankiweb-account-removal" 
"/extra-characters-appearing-on-cards.html" = "https://docs.ankiweb.net/faqs/extra-characters-appearing-on-cards" 
"/why-does-ankimobile-cost-more-than-a-typical-mobile-app.html" = "https://docs.ankiweb.net/faqs/why-does-ankimobile-cost-more-than-a-typical-mobile-app" 
"/frequently-asked-questions-about-fsrs.html" = "https://docs.ankiweb.net/faqs/frequently-asked-questions-about-fsrs" 
"/the-2021-scheduler.html" = "https://docs.ankiweb.net/faqs/the-2021-scheduler" 
"/anki-2.0-add-ons.html" = "https://docs.ankiweb.net/faqs/anki-2.0-add-ons" 
"/synchronizing-multiple-profiles.html" = "https://docs.ankiweb.net/faqs/synchronizing-multiple-profiles" 
"/some-updates-were-ignored-because-the-note-type-has-changed.html" = "https://docs.ankiweb.net/faqs/some-updates-were-ignored-because-the-note-type-has-changed" 
"/screenshots-large-and-blurry-on-retina-displays.html" = "https://docs.ankiweb.net/faqs/screenshots-large-and-blurry-on-retina-displays" 
"/the-anki-2.1-scheduler.html" = "https://docs.ankiweb.net/faqs/the-anki-2.1-scheduler" 
"/ankiuniversal-is-not-supported-here.html" = "https://docs.ankiweb.net/faqs/ankiuniversal-is-not-supported-here" 
"/running-from-python.html" = "https://docs.ankiweb.net/faqs/running-from-python" 
"/hiding-decks.html" = "https://docs.ankiweb.net/faqs/hiding-decks" 
"/we-do-not-make-robots.html" = "https://docs.ankiweb.net/faqs/we-do-not-make-robots" 
"/i-am-going-on-vacation-can-i-pause-the-scheduler.html" = "https://docs.ankiweb.net/faqs/i-am-going-on-vacation-can-i-pause-the-scheduler" 
"/a-shared-deck-is-not-showing-images-or-playing-audio.html" = "https://docs.ankiweb.net/faqs/a-shared-deck-is-not-showing-images-or-playing-audio" 
"/email-verification.html" = "https://docs.ankiweb.net/faqs/email-verification" 
"/anki-says-my-clock-is-wrong.html" = "https://docs.ankiweb.net/faqs/anki-says-my-clock-is-wrong" 
"/changing-the-interface-language.html" = "https://docs.ankiweb.net/faqs/changing-the-interface-language" 
"/can-i-use-anki-in-a-company-or-school.html" = "https://docs.ankiweb.net/faqs/can-i-use-anki-in-a-company-or-school" 
"/anki-must-be-able-to-connect-to-a-local-port.html" = "https://docs.ankiweb.net/faqs/anki-must-be-able-to-connect-to-a-local-port" 
"/ankiapp-is-not-part-of-the-anki-ecosystem.html" = "https://docs.ankiweb.net/faqs/ankiapp-is-not-part-of-the-anki-ecosystem" 
"/sounds-or-images-have-gone-missing.html" = "https://docs.ankiweb.net/faqs/sounds-or-images-have-gone-missing" 
"/card-template-has-a-problem.html" = "https://docs.ankiweb.net/faqs/card-template-has-a-problem" 
"/multiple-choice-questions.html" = "https://docs.ankiweb.net/faqs/multiple-choice-questions" 
"/characters-are-cut-off.html" = "https://docs.ankiweb.net/faqs/characters-are-cut-off" 
"/syncing-failed-connection-timed-out-errors-when-syncing.html" = "https://docs.ankiweb.net/faqs/syncing-failed-connection-timed-out-errors-when-syncing" 
"/what-spaced-repetition-algorithm.html" = "https://docs.ankiweb.net/faqs/what-spaced-repetition-algorithm" 
"/settings-for-using-anki-to-prepare-for-a-large-exam.html" = "https://docs.ankiweb.net/faqs/settings-for-using-anki-to-prepare-for-a-large-exam" 
"/sticky-fields.html" = "https://docs.ankiweb.net/faqs/sticky-fields" 
"/no-cloze-found-on-card.html" = "https://docs.ankiweb.net/faqs/no-cloze-found-on-card" 
"/merging-or-combining-two-decks.html" = "https://docs.ankiweb.net/faqs/merging-or-combining-two-decks" 
"/how-can-i-donate.html" = "https://docs.ankiweb.net/faqs/how-can-i-donate" 
"/timezone-handling-changes.html" = "https://docs.ankiweb.net/faqs/timezone-handling-changes" 
"/my-antivirus-program-says-anki-is-infected.html" = "https://docs.ankiweb.net/faqs/my-antivirus-program-says-anki-is-infected" 
"/customizing-mathjax.html" = "https://docs.ankiweb.net/faqs/customizing-mathjax" 
"/errors-when-recording.html" = "https://docs.ankiweb.net/faqs/errors-when-recording" 
"/hard-good-interval-longer-than-good-easy.html" = "https://docs.ankiweb.net/faqs/hard-good-interval-longer-than-good-easy" 
"/how-do-i-move-cards-between-decks.html" = "https://docs.ankiweb.net/faqs/how-do-i-move-cards-between-decks" 
"/printing-cards-in-your-collection.html" = "https://docs.ankiweb.net/faqs/printing-cards-in-your-collection" 
"/anki-2.0-support-has-ended.html" = "https://docs.ankiweb.net/faqs/anki-2.0-support-has-ended" 
"/cards-are-being-placed-in-the-default-deck.html" = "https://docs.ankiweb.net/faqs/cards-are-being-placed-in-the-default-deck" 
"/a-deck-i-want-has-disappeared-from-ankiweb.html" = "https://docs.ankiweb.net/faqs/a-deck-i-want-has-disappeared-from-ankiweb" 
"/retrieving-ankimobile-crash-logs.html" = "https://docs.ankiweb.net/faqs/retrieving-ankimobile-crash-logs" 
"/cards-are-reversed-appearing-twice.html" = "https://docs.ankiweb.net/faqs/cards-are-reversed-appearing-twice" 

